version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://root:1234@mongo:27017/'
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - '27017:27017'
    volumes:
      - /home/rafael/Development/courses/clean-ts-api/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

  api:
    container_name: api-container
    build: .
    image: clean-ts-api
    restart: always
    command: npm start
    volumes:
      - /home/rafael/Development/courses/clean-ts-api/dist
    ports:
      - '5050:5050'
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
